#!/bin/sh

if [ "$(whoami)" != "root" ]; then
  echo "Need to be root." >&2
  exit 1
fi

case "$1" in
  start)
    if [ -f /usr/bin/civetweb ] && [ -f /etc/civetweb.conf ]; then
      printf "Starting civetweb server ... "
      start-stop-daemon -S -q -m -b -p /var/run/civetweb.pid --exec /usr/bin/civetweb -- /etc/civetweb.conf
    elif [ -f /usr/sbin/httpd ] && [ -f /etc/httpd.conf ]; then
      printf "Starting httpd ... "
      /usr/sbin/httpd -u www-data:www-data -h /var/www -c /etc/httpd.conf
    fi
    ;;
  stop)
    printf "Stopping web server ..."
    start-stop-daemon -K -q -p /var/run/civetweb.pid &>/dev/null
    killall httpd &>/dev/null
    echo "done."
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
    ;;
esac

exit $?
