#!/bin/sh

if [ "$(whoami)" != "root" ]; then
  echo "Need to be root." >&2
  exit 1
fi

case "$1" in
  start|restart|reload)
    [ $(which connmanctl) != "" ] || exit 0
    connmanctl enable wifi
    ;;
  stop)
    exit 0
    ;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
