#!/bin/sh
export TERM=xterm
export PATH=/sbin:/usr/sbin:/bin:/usr/bin
export TZ=UTC
alias ll='ls --color=auto -lsiah'
alias la='ls --color=auto -Ah'
alias l='ls --color=auto -CFh'
alias ..='cd ..'
alias reset="echo -n -e '\0033\0143'"
alias su='su -l'

if [ "$(whoami)" = "root" ]; then
  PS1='\[\033[00;33m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[0;31m\]#\[\033[00m\] '
else
  PS1='\[\033[00;33m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[0;35m\]$\[\033[00m\] '
fi
